spring:
  application:
    name: E-Shop

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      max-lifetime: 180000
      idle-timeout: 170000

  sql:
    init:
      mode: always

  docker:
    compose:
      lifecycle-management: start_only
  modulith:
    detection-strategy: explicitly-annotated



logging:
  level:
    nu.westlin.eshop: debug
    root: warn

customer.loyalty.duration: 365d

events:
  minAge: 1m
  maxAttempts: 5