CREATE TABLE IF NOT EXISTS orders
(
    id          UUID PRIMARY KEY,
    customer_id UUID             NOT NULL,
    status      VARCHAR(20)      NOT NULL,
    discount    DOUBLE PRECISION NOT NULL,
    sub_total   INTEGER          NOT NULL,
    total_price INTEGER          NOT NULL
);

CREATE TABLE IF NOT EXISTS order_line_items
(
    id         BIGSERIAL PRIMARY KEY,
    order_id   UUID    NOT NULL,
    product_id INTEGER NOT NULL CHECK (id > 0),
    quantity   INT     NOT NULL CHECK (product_id > 0),
    price      INT     NOT NULL,

    CONSTRAINT fk_order_line_items_orders
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customers
(
    id    UUID PRIMARY KEY,
    name  VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL unique
);

CREATE TABLE IF NOT EXISTS products
(
    id          INTEGER     NOT NULL CHECK (id > 0) PRIMARY KEY,
    name        VARCHAR(20) NOT NULL,
    description VARCHAR(40) NOT NULL,
    price       INT         NOT NULL CHECK (price > 0)
);

CREATE TABLE IF NOT EXISTS customer_orders
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID        NOT NULL,
    order_id    UUID        NOT NULL,
    total_price INTEGER     NOT NULL,
    instant     TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_customer_order_customer_order UNIQUE (customer_id, order_id)
);

CREATE TABLE IF NOT EXISTS inventory_items
(
    product_id INTEGER PRIMARY KEY CHECK (product_id > 0),
    quantity   INT NOT NULL CHECK (quantity >= 0)
);
