CREATE TABLE IF NOT EXISTS orders
(
    id           UUID PRIMARY KEY,
    version      INTEGER          NOT NULL CHECK (version > 0),
    created_at   TIMESTAMPTZ      NOT NULL,
    updated_at   TIMESTAMPTZ      NOT NULL,
    customer_id  UUID             NOT NULL,
    status       VARCHAR(20)      NOT NULL,
    discount     DOUBLE PRECISION NOT NULL CHECK (discount >= 0),
    sub_total    INTEGER          NOT NULL CHECK (sub_total > 0),
    grand_total INTEGER NOT NULL CHECK (grand_total > 0),
    shipped_time TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS order_line_items
(
    id         BIGSERIAL PRIMARY KEY,
    order_id   UUID    NOT NULL,
    product_id INTEGER NOT NULL CHECK (id > 0),
    quantity   INT     NOT NULL CHECK (product_id > 0),
    price      INT     NOT NULL CHECK (price > 0),

    CONSTRAINT fk_order_line_items_orders
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customers
(
    id    UUID PRIMARY KEY,
    name  VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL unique
);

CREATE TABLE IF NOT EXISTS products
(
    id          INTEGER     NOT NULL CHECK (id > 0) PRIMARY KEY,
    name        VARCHAR(20) NOT NULL,
    description VARCHAR(40) NOT NULL,
    price       INT         NOT NULL CHECK (price > 0)
);

CREATE TABLE IF NOT EXISTS customer_orders
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID        NOT NULL,
    order_id    UUID        NOT NULL,
    grand_total INTEGER NOT NULL CHECK (grand_total > 0),
    instant     TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_customer_order_customer_order UNIQUE (customer_id, order_id)
);

CREATE TABLE IF NOT EXISTS inventory_items
(
    product_id INTEGER PRIMARY KEY CHECK (product_id > 0),
    version    INTEGER NOT NULL CHECK (version > 0),
    quantity   INT     NOT NULL CHECK (quantity >= 0)
);

CREATE TABLE IF NOT EXISTS reserved_inventory_items
(
    product_id INTEGER CHECK (product_id > 0),
    order_id   UUID NOT NULL,
    quantity   INT  NOT NULL CHECK (quantity >= 0),
    CONSTRAINT pk_reserved_inventory_items PRIMARY KEY (product_id, order_id)
);

CREATE TABLE IF NOT EXISTS app_users
(
    username VARCHAR(25) PRIMARY KEY,
    password VARCHAR(25)  NOT NULL,
    roles    VARCHAR(255) NOT NULL
);