### Skapa order bec7defb-1cfe-4af2-ba4a-74c438ce7eb1
POST http://localhost:8080/orders
Content-Type: application/json

{
  "orderId": "bec7defb-1cfe-4af2-ba4a-74c438ce7eb1",
  "customerId": "d9538d50-8976-4dea-9b5f-96ecf5bbafc5",
  "items": [
    {
      "productId": 1,
      "quantity": 22,
      "price": 7
    }
  ]
}
